# Generated by Django 6.0.7 on 2026-07-28 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(help_text="Model's predicted probability of academic risk (0-1).")),
                ('score', models.FloatField(help_text='Risk score on a 0-100 scale (higher = more at risk).')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('top_factors', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(default='v1', max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_alerts', to=settings.AUTH_USER_MODEL)),
                ('risk_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.riskscore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['student', '-computed_at'], name='analytics_r_student_ceaa9a_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['risk_level'], name='analytics_r_risk_le_5208ec_idx'),
        ),
        migrations.AddIndex(
            model_name='advisoralert',
            index=models.Index(fields=['status'], name='analytics_a_status_ec3d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='advisoralert',
            index=models.Index(fields=['student', 'status'], name='analytics_a_student_ac3002_idx'),
        ),
    ]
