# Generated by Django 6.0.7 on 2026-07-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='eligible_majors',
            field=models.JSONField(blank=True, default=list, help_text="List of target majors, e.g. ['Computer Science']. Empty list = open to all majors."),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='eligible_years',
            field=models.JSONField(blank=True, default=list, help_text='List of target academic years. Empty list = open to all years.'),
        ),
        migrations.AddField(
            model_name='financialaiditem',
            name='eligible_majors',
            field=models.JSONField(blank=True, default=list, help_text="List of eligible majors, e.g. ['Computer Science']. Empty list = open to all majors."),
        ),
        migrations.AddField(
            model_name='financialaiditem',
            name='eligible_years',
            field=models.JSONField(blank=True, default=list, help_text="List of eligible academic years, e.g. ['Junior', 'Senior']. Empty list = open to all years."),
        ),
        migrations.AddField(
            model_name='financialaiditem',
            name='min_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum GPA required (0.00-4.00). Blank = no GPA requirement.', max_digits=3, null=True),
        ),
    ]
