# Generated by Django 6.0.7 on 2026-08-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_supportticket_staff_note_supportticket_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
    ]
