# Generated by Django 6.0.7 on 2026-07-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], help_text="Student's current academic year (used for recommendations).", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative GPA on a 4.00 scale (used for recommendations).', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, help_text="Student's major/department (used for recommendations).", max_length=100, null=True),
        ),
    ]
