# Generated by Django 6.0.7 on 2026-08-04 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text="The student's assigned advisor. Only this advisor (plus admins) can see the student's risk/analytics data.", limit_choices_to={'role': 'advisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
    ]